[versions]

koin = "3.5.0"

[libraries]

android-material = { group = "com.google.android.material", name = "material", version = "1.9.0" }

androidx-annotation = { group = "androidx.annotation", name = "annotation", version = "1.7.0" }
androidx-ktx = { group = "androidx.core", name = "core-ktx", version = "1.12.0" }
androidx-constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version = "2.1.4" }
androidx-drawerlayout = { group = "androidx.drawerlayout", name = "drawerlayout", version = "1.2.0" }
androidx-fragment = { group = "androidx.fragment", name = "fragment-ktx", version = "1.6.1" }
androidx-gridlayout = { group = "androidx.gridlayout", name = "gridlayout", version = "1.0.0" }
androidx-lifecycle-runtime = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version = "2.6.2" }
androidx-lifecycle-viewmodel = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-ktx", version = "2.6.2" }
androidx-preference = { group = "androidx.preference", name = "preference-ktx", version = "1.2.1" }
androidx-recyclerview = { group = "androidx.recyclerview", name = "recyclerview", version = "1.3.1" }
androidx-transition = { group = "androidx.transition", name = "transition", version = "1.4.1" }
androidx-window = { group = "androidx.window", name = "window", version = "1.1.0" }

koin-core = { group = "io.insert-koin", name = "koin-core", version.ref = "koin" }
koin-android = { group = "io.insert-koin", name = "koin-android", version.ref = "koin" }

thirdparty-konfetti = { group = "nl.dionsegijn", name = "konfetti-xml", version = "2.0.3" }
thirdparty-ferriswheel = { group = "ru.github.igla", name = "ferriswheel", version = "1.2" }

[plugins]
